### ISSUE TITLE
How do I reproduce Figure S8?

### ISSUE THREAD

**Issue by raven38** [harskish/ganspace#19]
I want to reproduce the results of Figure S8 in your paper. 

Could you share the code snippets or some details?

**Comment by harskish** [comment]
S8 was created by a collaborator, and the code is unfortunately not included in this repo.

You might want to take a look at the functions `project_ortho` and `get_batch` in [notebooks/figure_style_content_sep.ipynb](https://github.com/harskish/ganspace/blob/master/notebooks/figure_style_content_sep.ipynb).
Instead of transferring coordinates from a second image, you can set them to zero, which is what is done in S8.

Hope this helps.
