### ISSUE TITLE
Manipulating my own npy file

### ISSUE THREAD

**Issue by ahmetdadak** [harskish/ganspace#26]
Hello Sir,
I am a newbie. I am trying to manipulate (changing smile, age, gender...) an image encoded by StyleGAN2 (using pixel2style2pixel). I have a .npy file (shape (18,512)). I want it to manipulate using your repository but I don't know how to do it. Is there a way to do so?

**Comment by harskish** [comment]
`notebooks/figure_teaser.ipynb` is a good place to start. The line `w = [w]*model.get_max_latents()` creates a list of 18 (1,512) vectors, which matches what you have. The editing itself is just applying offsets individually to each of the 18 layers:
```
for l in range(start, end):
    w[l] = w[l] + lat_comp[idx]*lat_std[idx]*delta
```

In order to find the component indices (idx) and layer ranges (start, end), you'd have to use one of our exploration tools, either `interactive.py` or the [Colab Notebook](https://colab.research.google.com/github/harskish/ganspace/blob/master/notebooks/Ganspace_colab.ipynb)

One thing to keep in mind is that, for common edits such as smile or gender, you might be better off using supervised methods such as [InterFaceGAN ](https://github.com/genforce/interfacegan). Our approach is best suited for exploring new datasets and finding uncommon edits.
